/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <CommandInterface.h>

#include <yarp/os/idl/WireTypes.h>

#include <algorithm>

// perform_joint_space_action helper class declaration
class CommandInterface_perform_joint_space_action_helper :
        public yarp::os::Portable
{
public:
    CommandInterface_perform_joint_space_action_helper() = default;
    explicit CommandInterface_perform_joint_space_action_helper(const std::string& actionName);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        explicit Command(const std::string& actionName);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::string actionName{};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::string&);
    void call(CommandInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"perform_joint_space_action"};
    static constexpr size_t s_tag_len{4};
    static constexpr size_t s_cmd_len{5};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool CommandInterface::perform_joint_space_action(const std::string& actionName)"};
    static constexpr const char* s_help{""};
};

// move_joints_to_position helper class declaration
class CommandInterface_move_joints_to_position_helper :
        public yarp::os::Portable
{
public:
    CommandInterface_move_joints_to_position_helper() = default;
    CommandInterface_move_joints_to_position_helper(const std::vector<double>& position, const double time);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        Command(const std::vector<double>& position, const double time);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::vector<double> position{};
        double time{0.0};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::vector<double>&, const double);
    void call(CommandInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"move_joints_to_position"};
    static constexpr size_t s_tag_len{4};
    static constexpr size_t s_cmd_len{6};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool CommandInterface::move_joints_to_position(const std::vector<double>& position, const double time)"};
    static constexpr const char* s_help{""};
};

// optimise_stiffness helper class declaration
class CommandInterface_optimise_stiffness_helper :
        public yarp::os::Portable
{
public:
    CommandInterface_optimise_stiffness_helper() = default;
    explicit CommandInterface_optimise_stiffness_helper(const std::vector<double>& direction);
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        explicit Command(const std::vector<double>& direction);

        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);

        std::vector<double> direction{};
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;

        bool return_helper{false};
    };

    using funcptr_t = bool (*)(const std::vector<double>&);
    void call(CommandInterface* ptr);

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"optimise_stiffness"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{3};
    static constexpr size_t s_reply_len{1};
    static constexpr const char* s_prototype{"bool CommandInterface::optimise_stiffness(const std::vector<double>& direction)"};
    static constexpr const char* s_help{""};
};

// stop helper class declaration
class CommandInterface_stop_helper :
        public yarp::os::Portable
{
public:
    CommandInterface_stop_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;
    };

    using funcptr_t = void (*)();
    void call(CommandInterface* ptr) const;

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"stop"};
    static constexpr size_t s_tag_len{1};
    static constexpr size_t s_cmd_len{1};
    static constexpr size_t s_reply_len{0};
    static constexpr const char* s_prototype{"void CommandInterface::stop()"};
    static constexpr const char* s_help{""};
};

// shut_down helper class declaration
class CommandInterface_shut_down_helper :
        public yarp::os::Portable
{
public:
    CommandInterface_shut_down_helper() = default;
    bool write(yarp::os::ConnectionWriter& connection) const override;
    bool read(yarp::os::ConnectionReader& connection) override;

    class Command :
            public yarp::os::idl::WirePortable
    {
    public:
        Command() = default;
        ~Command() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool writeTag(const yarp::os::idl::WireWriter& writer) const;
        bool writeArgs(const yarp::os::idl::WireWriter& writer) const;

        bool read(yarp::os::idl::WireReader& reader) override;
        bool readTag(yarp::os::idl::WireReader& reader);
        bool readArgs(yarp::os::idl::WireReader& reader);
    };

    class Reply :
            public yarp::os::idl::WirePortable
    {
    public:
        Reply() = default;
        ~Reply() override = default;

        bool write(yarp::os::ConnectionWriter& connection) const override;
        bool read(yarp::os::ConnectionReader& connection) override;

        bool write(const yarp::os::idl::WireWriter& writer) const override;
        bool read(yarp::os::idl::WireReader& reader) override;
    };

    using funcptr_t = void (*)();
    void call(CommandInterface* ptr) const;

    Command cmd;
    Reply reply;

    static constexpr const char* s_tag{"shut_down"};
    static constexpr size_t s_tag_len{2};
    static constexpr size_t s_cmd_len{2};
    static constexpr size_t s_reply_len{0};
    static constexpr const char* s_prototype{"void CommandInterface::shut_down()"};
    static constexpr const char* s_help{""};
};

// perform_joint_space_action helper class implementation
CommandInterface_perform_joint_space_action_helper::CommandInterface_perform_joint_space_action_helper(const std::string& actionName) :
        cmd{actionName}
{
}

bool CommandInterface_perform_joint_space_action_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool CommandInterface_perform_joint_space_action_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

CommandInterface_perform_joint_space_action_helper::Command::Command(const std::string& actionName) :
        actionName{actionName}
{
}

bool CommandInterface_perform_joint_space_action_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool CommandInterface_perform_joint_space_action_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool CommandInterface_perform_joint_space_action_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool CommandInterface_perform_joint_space_action_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool CommandInterface_perform_joint_space_action_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeString(actionName)) {
        return false;
    }
    return true;
}

bool CommandInterface_perform_joint_space_action_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool CommandInterface_perform_joint_space_action_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_perform_joint_space_action_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readString(actionName)) {
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_perform_joint_space_action_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool CommandInterface_perform_joint_space_action_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool CommandInterface_perform_joint_space_action_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool CommandInterface_perform_joint_space_action_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void CommandInterface_perform_joint_space_action_helper::call(CommandInterface* ptr)
{
    reply.return_helper = ptr->perform_joint_space_action(cmd.actionName);
}

// move_joints_to_position helper class implementation
CommandInterface_move_joints_to_position_helper::CommandInterface_move_joints_to_position_helper(const std::vector<double>& position, const double time) :
        cmd{position, time}
{
}

bool CommandInterface_move_joints_to_position_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool CommandInterface_move_joints_to_position_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

CommandInterface_move_joints_to_position_helper::Command::Command(const std::vector<double>& position, const double time) :
        position{position},
        time{time}
{
}

bool CommandInterface_move_joints_to_position_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool CommandInterface_move_joints_to_position_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool CommandInterface_move_joints_to_position_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool CommandInterface_move_joints_to_position_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool CommandInterface_move_joints_to_position_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeListBegin(BOTTLE_TAG_FLOAT64, position.size())) {
        return false;
    }
    if (!writer.writeBlock(reinterpret_cast<const char*>(position.data()), position.size() * sizeof(double))) {
        return false;
    }
    if (!writer.writeListEnd()) {
        return false;
    }
    if (!writer.writeFloat64(time)) {
        return false;
    }
    return true;
}

bool CommandInterface_move_joints_to_position_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool CommandInterface_move_joints_to_position_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_move_joints_to_position_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    size_t _csize;
    yarp::os::idl::WireState _etype;
    reader.readListBegin(_etype, _csize);
    // WireReader removes BOTTLE_TAG_LIST from the tag
    constexpr int expected_tag = ((BOTTLE_TAG_FLOAT64) & (~BOTTLE_TAG_LIST));
    if constexpr (expected_tag != 0) {
        if (_csize != 0 && _etype.code != expected_tag) {
            return false;
        }
    }
    position.resize(_csize);
    if (_csize != 0 && !reader.readBlock(reinterpret_cast<char*>(position.data()), position.size() * sizeof(double))) {
        return false;
    }
    reader.readListEnd();
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readFloat64(time)) {
        reader.fail();
        return false;
    }
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_move_joints_to_position_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool CommandInterface_move_joints_to_position_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool CommandInterface_move_joints_to_position_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool CommandInterface_move_joints_to_position_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void CommandInterface_move_joints_to_position_helper::call(CommandInterface* ptr)
{
    reply.return_helper = ptr->move_joints_to_position(cmd.position, cmd.time);
}

// optimise_stiffness helper class implementation
CommandInterface_optimise_stiffness_helper::CommandInterface_optimise_stiffness_helper(const std::vector<double>& direction) :
        cmd{direction}
{
}

bool CommandInterface_optimise_stiffness_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool CommandInterface_optimise_stiffness_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

CommandInterface_optimise_stiffness_helper::Command::Command(const std::vector<double>& direction) :
        direction{direction}
{
}

bool CommandInterface_optimise_stiffness_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool CommandInterface_optimise_stiffness_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool CommandInterface_optimise_stiffness_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool CommandInterface_optimise_stiffness_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool CommandInterface_optimise_stiffness_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeListBegin(BOTTLE_TAG_FLOAT64, direction.size())) {
        return false;
    }
    if (!writer.writeBlock(reinterpret_cast<const char*>(direction.data()), direction.size() * sizeof(double))) {
        return false;
    }
    if (!writer.writeListEnd()) {
        return false;
    }
    return true;
}

bool CommandInterface_optimise_stiffness_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool CommandInterface_optimise_stiffness_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_optimise_stiffness_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    size_t _csize;
    yarp::os::idl::WireState _etype;
    reader.readListBegin(_etype, _csize);
    // WireReader removes BOTTLE_TAG_LIST from the tag
    constexpr int expected_tag = ((BOTTLE_TAG_FLOAT64) & (~BOTTLE_TAG_LIST));
    if constexpr (expected_tag != 0) {
        if (_csize != 0 && _etype.code != expected_tag) {
            return false;
        }
    }
    direction.resize(_csize);
    if (_csize != 0 && !reader.readBlock(reinterpret_cast<char*>(direction.data()), direction.size() * sizeof(double))) {
        return false;
    }
    reader.readListEnd();
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_optimise_stiffness_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool CommandInterface_optimise_stiffness_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool CommandInterface_optimise_stiffness_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
        if (!writer.writeBool(return_helper)) {
            return false;
        }
    }
    return true;
}

bool CommandInterface_optimise_stiffness_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    if (reader.noMore()) {
        reader.fail();
        return false;
    }
    if (!reader.readBool(return_helper)) {
        reader.fail();
        return false;
    }
    return true;
}

void CommandInterface_optimise_stiffness_helper::call(CommandInterface* ptr)
{
    reply.return_helper = ptr->optimise_stiffness(cmd.direction);
}

// stop helper class implementation
bool CommandInterface_stop_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool CommandInterface_stop_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool CommandInterface_stop_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool CommandInterface_stop_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool CommandInterface_stop_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool CommandInterface_stop_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool CommandInterface_stop_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool CommandInterface_stop_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool CommandInterface_stop_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_stop_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_stop_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool CommandInterface_stop_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool CommandInterface_stop_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
    }
    return true;
}

bool CommandInterface_stop_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    return true;
}

void CommandInterface_stop_helper::call(CommandInterface* ptr) const
{
    ptr->stop();
}

// shut_down helper class implementation
bool CommandInterface_shut_down_helper::write(yarp::os::ConnectionWriter& connection) const
{
    return cmd.write(connection);
}

bool CommandInterface_shut_down_helper::read(yarp::os::ConnectionReader& connection)
{
    return reply.read(connection);
}

bool CommandInterface_shut_down_helper::Command::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    if (!writer.writeListHeader(s_cmd_len)) {
        return false;
    }
    return write(writer);
}

bool CommandInterface_shut_down_helper::Command::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }
    return read(reader);
}

bool CommandInterface_shut_down_helper::Command::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writeTag(writer)) {
        return false;
    }
    if (!writeArgs(writer)) {
        return false;
    }
    return true;
}

bool CommandInterface_shut_down_helper::Command::writeTag(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.writeTag(s_tag, 1, s_tag_len)) {
        return false;
    }
    return true;
}

bool CommandInterface_shut_down_helper::Command::writeArgs(const yarp::os::idl::WireWriter& writer [[maybe_unused]]) const
{
    return true;
}

bool CommandInterface_shut_down_helper::Command::read(yarp::os::idl::WireReader& reader)
{
    if (!readTag(reader)) {
        return false;
    }
    if (!readArgs(reader)) {
        return false;
    }
    return true;
}

bool CommandInterface_shut_down_helper::Command::readTag(yarp::os::idl::WireReader& reader)
{
    std::string tag = reader.readTag(s_tag_len);
    if (reader.isError()) {
        return false;
    }
    if (tag != s_tag) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_shut_down_helper::Command::readArgs(yarp::os::idl::WireReader& reader)
{
    if (!reader.noMore()) {
        reader.fail();
        return false;
    }
    return true;
}

bool CommandInterface_shut_down_helper::Reply::write(yarp::os::ConnectionWriter& connection) const
{
    yarp::os::idl::WireWriter writer(connection);
    return write(writer);
}

bool CommandInterface_shut_down_helper::Reply::read(yarp::os::ConnectionReader& connection)
{
    yarp::os::idl::WireReader reader(connection);
    return read(reader);
}

bool CommandInterface_shut_down_helper::Reply::write(const yarp::os::idl::WireWriter& writer) const
{
    if (!writer.isNull()) {
        if (!writer.writeListHeader(s_reply_len)) {
            return false;
        }
    }
    return true;
}

bool CommandInterface_shut_down_helper::Reply::read(yarp::os::idl::WireReader& reader)
{
    if (!reader.readListReturn()) {
        return false;
    }
    return true;
}

void CommandInterface_shut_down_helper::call(CommandInterface* ptr) const
{
    ptr->shut_down();
}

// Constructor
CommandInterface::CommandInterface()
{
    yarp().setOwner(*this);
}

bool CommandInterface::perform_joint_space_action(const std::string& actionName)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", CommandInterface_perform_joint_space_action_helper::s_prototype);
    }
    CommandInterface_perform_joint_space_action_helper helper{actionName};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool CommandInterface::move_joints_to_position(const std::vector<double>& position, const double time)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", CommandInterface_move_joints_to_position_helper::s_prototype);
    }
    CommandInterface_move_joints_to_position_helper helper{position, time};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

bool CommandInterface::optimise_stiffness(const std::vector<double>& direction)
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", CommandInterface_optimise_stiffness_helper::s_prototype);
    }
    CommandInterface_optimise_stiffness_helper helper{direction};
    bool ok = yarp().write(helper, helper);
    return ok ? helper.reply.return_helper : bool{};
}

void CommandInterface::stop()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", CommandInterface_stop_helper::s_prototype);
    }
    CommandInterface_stop_helper helper{};
    yarp().write(helper, helper);
}

void CommandInterface::shut_down()
{
    if (!yarp().canWrite()) {
        yError("Missing server method '%s'?", CommandInterface_shut_down_helper::s_prototype);
    }
    CommandInterface_shut_down_helper helper{};
    yarp().write(helper, helper);
}

// help method
std::vector<std::string> CommandInterface::help(const std::string& functionName)
{
    bool showAll = (functionName == "--all");
    std::vector<std::string> helpString;
    if (showAll) {
        helpString.emplace_back("*** Available commands:");
        helpString.emplace_back(CommandInterface_perform_joint_space_action_helper::s_tag);
        helpString.emplace_back(CommandInterface_move_joints_to_position_helper::s_tag);
        helpString.emplace_back(CommandInterface_optimise_stiffness_helper::s_tag);
        helpString.emplace_back(CommandInterface_stop_helper::s_tag);
        helpString.emplace_back(CommandInterface_shut_down_helper::s_tag);
        helpString.emplace_back("help");
    } else {
        if (functionName == CommandInterface_perform_joint_space_action_helper::s_tag) {
            helpString.emplace_back(CommandInterface_perform_joint_space_action_helper::s_prototype);
        }
        if (functionName == CommandInterface_move_joints_to_position_helper::s_tag) {
            helpString.emplace_back(CommandInterface_move_joints_to_position_helper::s_prototype);
        }
        if (functionName == CommandInterface_optimise_stiffness_helper::s_tag) {
            helpString.emplace_back(CommandInterface_optimise_stiffness_helper::s_prototype);
        }
        if (functionName == CommandInterface_stop_helper::s_tag) {
            helpString.emplace_back(CommandInterface_stop_helper::s_prototype);
        }
        if (functionName == CommandInterface_shut_down_helper::s_tag) {
            helpString.emplace_back(CommandInterface_shut_down_helper::s_prototype);
        }
        if (functionName == "help") {
            helpString.emplace_back("std::vector<std::string> help(const std::string& functionName = \"--all\")");
            helpString.emplace_back("Return list of available commands, or help message for a specific function");
            helpString.emplace_back("@param functionName name of command for which to get a detailed description. If none or '--all' is provided, print list of available commands");
            helpString.emplace_back("@return list of strings (one string per line)");
        }
    }
    if (helpString.empty()) {
        helpString.emplace_back("Command not found");
    }
    return helpString;
}

// read from ConnectionReader
bool CommandInterface::read(yarp::os::ConnectionReader& connection)
{
    constexpr size_t max_tag_len = 4;
    size_t tag_len = 1;

    yarp::os::idl::WireReader reader(connection);
    reader.expectAccept();
    if (!reader.readListHeader()) {
        reader.fail();
        return false;
    }

    std::string tag = reader.readTag(1);
    bool direct = (tag == "__direct__");
    if (direct) {
        tag = reader.readTag(1);
    }
    while (tag_len <= max_tag_len && !reader.isError()) {
        if (tag == CommandInterface_perform_joint_space_action_helper::s_tag) {
            CommandInterface_perform_joint_space_action_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == CommandInterface_move_joints_to_position_helper::s_tag) {
            CommandInterface_move_joints_to_position_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == CommandInterface_optimise_stiffness_helper::s_tag) {
            CommandInterface_optimise_stiffness_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == CommandInterface_stop_helper::s_tag) {
            CommandInterface_stop_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == CommandInterface_shut_down_helper::s_tag) {
            CommandInterface_shut_down_helper helper;
            if (!helper.cmd.readArgs(reader)) {
                return false;
            }

            helper.call(this);

            yarp::os::idl::WireWriter writer(reader);
            if (!helper.reply.write(writer)) {
                return false;
            }
            reader.accept();
            return true;
        }
        if (tag == "help") {
            std::string functionName;
            if (!reader.readString(functionName)) {
                functionName = "--all";
            }
            auto help_strings = help(functionName);
            yarp::os::idl::WireWriter writer(reader);
            if (!writer.isNull()) {
                if (!writer.writeListHeader(2)) {
                    return false;
                }
                if (!writer.writeTag("many", 1, 0)) {
                    return false;
                }
                if (!writer.writeListBegin(0, help_strings.size())) {
                    return false;
                }
                for (const auto& help_string : help_strings) {
                    if (!writer.writeString(help_string)) {
                        return false;
                    }
                }
                if (!writer.writeListEnd()) {
                    return false;
                }
            }
            reader.accept();
            return true;
        }
        if (reader.noMore()) {
            reader.fail();
            return false;
        }
        std::string next_tag = reader.readTag(1);
        if (next_tag.empty()) {
            break;
        }
        tag.append("_").append(next_tag);
        tag_len = std::count(tag.begin(), tag.end(), '_') + 1;
    }
    return false;
}
